name: Build & Test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://roviapps/android-sdk
      - name: Build
        run: gradle build
      - name: Lint
        run: gradle ktlint
