name: Style
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: alejandrorosas/android:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: gradle build
      - name: ktlint
        run: gradle ktlint
