name: Build & Test
on:
 push:
  branches:
   - master
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@master
   - uses: docker://roviapps/android-sdk
   - run: gradle build
   - run: gradle ktlint

